INSERT INTO PCNFENTPISCOFINS
 (NUMTRANSENT, CODTRIBPISCOFINS, VLBASEPIS,  VLBASECOFINS, PERPIS, PERCOFINS, VLPIS, VLCOFINS, NATCREDITO, NUMTRANSPISCOFINS, PERCREDBASEPISCOFINSFRETE, CODCONT )
VALUES
 (:NUMTRANSENT, :CODTRIBPISCOFINS, :VLBASEPIS,  :VLBASECOFINS, :PERPIS, :PERCOFINS, :VLPIS, :VLCOFINS, :NATCREDITO, :NUMTRANSPISCOFINS, :PERCREDBASEPISCOFINSFRETE, :CODCONT)

