select ESPECIE,SERIE,NUMNOTA,DTEMISSAO,DTENT,CODFORNEC,VLTOTAL,CODCONT,CODFISCAL,CODFILIAL,
TIPODESCARGA,NUMTRANSENT,VLIPI,VLFRETE,VLST,VLDESCONTO,VLBASEIPI,UF,
VLOUTRAS,CODFUNCLANC,HORALANC,MINUTOLANC
ROTINALANC,FUNCLANC,CHAVENFE,SITUACAONFE,EMISSAOPROPRIA,TIPOEMISSAO,FORNECEDOR,
CGC,IE,TIPOFJ,TIPOFORNEC,CODPAIS,DESCPAIS,CGCFILIAL,IEFILIAL,UFFILIAL,CODFORFILIAL,
TIPOALIQOUTRASDESP,CODCONTFOR,CODCONTFRE,TIPOFRETECIFFOB,REVENDA,
UFCODIGO,HISTORICO,DTLANCTO,ENDERECO,BAIRRO,MUNICIPIO,CEP,CODMUNICIPIO,CONSUMIDORFINAL,
CODIBGE,SIMPLESNACIONAL
 from pcnfent where numtransent = 852712





